"""group_practice

Revision ID: d6598fdcef7c
Revises: ddf4c59afa8a
Create Date: 2024-12-08 12:42:53.496668

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d6598fdcef7c"
down_revision: Union[str, None] = "ddf4c59afa8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_practice",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("practice_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["practice_id"],
            ["practices.id"],
        ),
        sa.UniqueConstraint("group_id", "practice_id", name="uq_group_practice"),
    )
    op.drop_column("practices", "pattern_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "practices",
        sa.Column("pattern_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_table("group_practice")
    # ### end Alembic commands ###
