"""module update

Revision ID: 05c0b3ed7917
Revises: 55e3c0a41bb6
Create Date: 2024-11-21 11:18:23.815144

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "05c0b3ed7917"
down_revision: Union[str, None] = "55e3c0a41bb6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("modules", sa.Column("creator_id", sa.Integer(), nullable=False))
    op.add_column("modules", sa.Column("is_mandatory", sa.Boolean(), nullable=False))
    op.create_foreign_key(None, "modules", "users", ["creator_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "modules", type_="foreignkey")
    op.drop_column("modules", "is_mandatory")
    op.drop_column("modules", "creator_id")
    # ### end Alembic commands ###
