"""groups

Revision ID: e24189375df4
Revises: 05c0b3ed7917
Create Date: 2024-12-07 20:28:18.948989

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e24189375df4"
down_revision: Union[str, None] = "05c0b3ed7917"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(length=7), nullable=False),
        sa.Column("specialization_id", sa.Integer(), nullable=False),
        sa.Column("course", sa.Integer(), nullable=False),
        sa.CheckConstraint("course >= 2 AND course <= 4", name="check_course_range"),
        sa.ForeignKeyConstraint(
            ["specialization_id"],
            ["specializations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number"),
        sa.UniqueConstraint(
            "specialization_id", "course", name="unique_specialization_course"
        ),
    )
    op.drop_constraint(
        "lesson_results_student_id_fkey", "lesson_results", type_="foreignkey"
    )
    op.create_foreign_key(None, "lesson_results", "users", ["student_id"], ["id"])
    op.drop_constraint("specializations_code_key", "specializations", type_="unique")
    op.drop_column("specializations", "code")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "specializations",
        sa.Column("code", sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    )
    op.create_unique_constraint("specializations_code_key", "specializations", ["code"])
    op.drop_constraint(None, "lesson_results", type_="foreignkey")
    op.create_foreign_key(
        "lesson_results_student_id_fkey",
        "lesson_results",
        "lessons",
        ["student_id"],
        ["id"],
    )
    op.drop_table("groups")
    # ### end Alembic commands ###
