"""group UniqueConstraint update

Revision ID: 63bb285adba1
Revises: 3e404ec2f69e
Create Date: 2024-12-08 11:06:41.987709

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "63bb285adba1"
down_revision: Union[str, None] = "3e404ec2f69e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_specialization_course", "groups", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_specialization_course", "groups", ["specialization_id", "course"]
    )
    # ### end Alembic commands ###
