"""practice

Revision ID: 18c9657ec5c2
Revises: 5834fc9fcbfa
Create Date: 2024-11-18 17:50:12.603027

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18c9657ec5c2"
down_revision: Union[str, None] = "5834fc9fcbfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "specializations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=7), nullable=True),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "practice_patterns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("EDUCATIONAL_PRACTICE", "PRODUCTION_PRACTICE", name="practicetype"),
            nullable=False,
        ),
        sa.Column("specialization_id", sa.Integer(), nullable=False),
        sa.Column("course_number", sa.CHAR(), nullable=False),
        sa.ForeignKeyConstraint(
            ["specialization_id"],
            ["specializations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "practices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=False),
        sa.Column("pattern_id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("start_at", sa.DateTime(), nullable=True),
        sa.Column("end_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pattern_id"],
            ["practice_patterns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "practice_developers",
        sa.Column("practice_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["practice_id"],
            ["practices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.UniqueConstraint("practice_id", "user_id", name="uq_practice_developers"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("practice_developers")
    op.drop_table("practices")
    op.drop_table("practice_patterns")
    op.drop_table("specializations")
    # ### end Alembic commands ###
