"""add cpecilaization code

Revision ID: 3e404ec2f69e
Revises: dee95f49f27a
Create Date: 2024-12-08 10:15:30.196917

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e404ec2f69e"
down_revision: Union[str, None] = "dee95f49f27a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "specializations", sa.Column("code", sa.String(length=3), nullable=False)
    )
    op.create_unique_constraint(None, "specializations", ["code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "specializations", type_="unique")
    op.drop_column("specializations", "code")
    # ### end Alembic commands ###
